[tool.poetry]
name = "cyclonedx"
version = "0.0.1"
description = "A library for producing CycloneDX SBOM (Software Bill of Materials) files."
authors = ["Paul Horton <phorton@sonatype.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
packageurl-python = "^0.9.4"
requirements_parser = "^0.2.0"
setuptools = "^50.3.2"

[tool.poetry.dev-dependencies]
tox = "^3.24.3"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"