# Copyright 2019-present Sonatype Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

executors:
  python39:
    docker:
      - image: circleci/python:3.9

jobs:
  publish:
    executor: python39
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - add_ssh_keys:
          fingerprints:
            # TODO: change fingerprint
            - "4f:7d:6b:26:dc:44:de:b0:4d:f1:96:50:2a:b5:bd:b3"
      - checkout
      - run:
          name: Setup Python environment
          command: |
            # TODO: do stuff, like setup venv, poetry, pip etc
      - run:
          command: |
            # TODO: perform publish steps, maybe using python-semantic-release

  build:
    executor: python39
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Install Tox & Coverage
          command: |
            pip install tox coverage
      - run:
          name: Run tox
          command: |
            tox --result-json=.tox/results.json
      - run:
          name: Generate Coverage Reports
          command: |
            coverage report && coverage xml -o test-reports/coverage.xml
      - run:
          name: Run self scan
          command: |
            # TODO: audit with jake maybe?
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: .tox/results.json
          destination: tox-logs
      - store_test_results:
          path: test-reports

workflows:
  version: 2
  build_and_test_and_publish:
    jobs:
      - build
#  TODO: enable to publish after successful build
#      - publish:
#          filters:
#            branches:
#              only: main
#          context: pypi
#          requires:
#            - build

  build_nightly:
    triggers:
      - schedule:
          cron: "35 20 * * *"
          filters:
            branches:
              only: main
    jobs:
      - build
